name: orispay.com
favicon: null
layout_spectrum: 0.4609373651910573
typography_spectrum: 0.6457193014211953
title: ORISPAY - Paiement électronique
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2091827178373933
  lightness: 0.4673246429301798
  saturation: 0.7591538575943559
  rhythmicContrast: 0.4230198098812252
purpose: []
